{{- $ss_name := include "common.names.fullname" . -}}
---
{{- if .Values.externalSecret.enabled }}
apiVersion: {{ .Values.externalSecretApiVersion | default "external-secrets.io/v1beta1" }}
kind: ExternalSecret
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  dataFrom:
  - extract:
      conversionStrategy: {{ .Values.externalSecret.conversionStrategy | default "Default" }}
      decodingStrategy: {{ .Values.externalSecret.decodingStrategy | default "None" }}
      key: {{ .Values.externalSecret.secretPath }}
  refreshInterval: {{ .Values.externalSecret.refreshInterval | default "5s" }}
  secretStoreRef:
    kind: {{ .Values.externalSecret.secretStoreKind | default "SecretStore" }}
    name: {{ .Values.externalSecret.secretStoreName | default $ss_name }}
  target:
    creationPolicy: {{ .Values.externalSecret.creationPolicy | default "Owner" }}
    deletionPolicy: {{ .Values.externalSecret.deletionPolicy | default "Retain" }}
    name: {{ template "common.names.fullname" . }}-external-secret
{{- end }}