{{- if .Values.secretStore.enabled }}
apiVersion: {{ .Values.externalSecretApiVersion | default "external-secrets.io/v1beta1" }}
kind: SecretStore
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  retrySettings:
    maxRetries: {{ .Values.secretStore.maxRetries | default "5"}}
    retryInterval: {{ .Values.secretStore.retryInterval | default "10s" }}
  provider:
{{- toYaml .Values.secretStore.provider | nindent 4 }}
{{- end }}